### ISSUE TITLE
About read length filter. Will it be a problem if I include reads shoter than 10kb?

### ISSUE THREAD

**Issue by ItokawaK** [lbcb-sci/herro#15]
Hello

I have used herro for several data sets of insect whole genome sequence, and obtained amazing results.
Herro + hifiasm generated more contiguous and high BUSCO score assemblies compared to flye while demanding less amount of memory.

- Question
It seems that `preprocess.sh` omits reads shoter than 10,000 bp.
Is it because it's nesessary, or is it no problem to include shoter reads when assembling relatively small genomes?

Thanks

**Comment by dehui333** [comment]
Hi, it's good to hear that you are obtaining good results with herro.

Regarding the length of input reads for correction, there are a few things to note:
1. Reads are corrected in windows of around 4096 bp and reads that are shorter than that won't be corrected even if they are in the input file.
2. Reads that are longer than that minimum requirement might be corrected if enough good overlaps are found. We have observed better correction performance (in terms of assembly metrics) with longer reads before. However, I think you can try correcting without filtering to >= 10,000 bp if there is a reason to do so, though reads shorter than ~4kbp would be lost anyway.  

Best,
Dehui

**Comment by ItokawaK** [comment]
Dehui

I understand. Thank you! 

Kentaro
