### ISSUE TITLE
batch.py syntax error

### ISSUE THREAD

**Issue by evgenyleushkin** [lbcb-sci/herro#22]
I'm getting following sequence error for **batch.py** script  

File "./batch.py", line 43
    if (idx := rids.get(tname, None)) is not None:
            ^
SyntaxError: invalid syntax

**Comment by dominikstanojevic** [comment]
Hello Evgeny,

The Walrus operator introduced in Python 3.8 could be the problem. Can you check your Python version?

**Comment by evgenyleushkin** [comment]
Thanks a lot for a quick reply. 
I get this error for 3.7.12. Which version do you recommend?

**Comment by dominikstanojevic** [comment]
Hello Evgeny,

as I mentioned previously, the Walrus operator was introduced in Python 3.8. I would always recommend the latest version (if compatible with all the packages) which is 3.12.

Closing this since we found the problem.

**Comment by mb47** [comment]
Hi,
I had the same problem and fixed this by creating a conda environment for python 3.12 which I then activate before running the create_batched_alignments.sh script. However, now there is a new problem:

[ERROR] unknown option in "-w17"
Traceback (most recent call last):
  File "/mnt/shared/scratch/mbayer/apps//herro/herro/scripts/batch.py", line 3, in <module>
    import zstandard as zstd
ModuleNotFoundError: No module named 'zstandard'

So this looks to me like the script requires a module which is now missing from this later version of Python. Could you help please? 

thanks
Micha

**Comment by sirselim** [comment]
@mb47 - when you set up your latest conda env did you make sure to install the dependancies as instructed in the readme ([here](https://github.com/lbcb-sci/herro/tree/main?tab=readme-ov-file#installation))? i.e. `conda env create --file scripts/herro-env.yml`

The `scripts/herro-env.yml` file contains all the dependancies required for the herro scripts to run. So it's likely not that the zstandard package is missing from Python, it's just that it hasn't been installed in your environment.

If you create the above environment you might need to remove the porechop dependancy from the yml file, that fork doesn't exist and will likely cause the environment creation to error out.

You can also manually install packages in environments with something like: `conda install zstandard`
