### ISSUE TITLE
Installation issues during conda env create

### ISSUE THREAD

**Issue by Krannich479** [lbcb-sci/herro#26]
Hey herro team, 
I'd like to test `herro` but unfortunately I face issues with installation step 1, the conda environment. The build fails when trying to download `Porechop` via pip. Do you see anything being wrong about my setup or the way I am installing herro?

- **Error message:**
<details><summary> ⚠️ Expand error log here </summary>
<code>
$ conda env create --file scripts/herro-env.yml
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done
Downloading and Extracting Packages:
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Username for 'https://github.com'-/
Password for 'https://krannich479@github.com'-/
Ran pip subprocess with arguments:
['/path/to/miniconda3/envs/herro/bin/python', '-m', 'pip', 'install', '-U', '-r', '/path/to/herro/scripts/condaenv.qnqwyn6k.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/dehui333/Porechop.git (from -r /path/to/herro/scripts/condaenv.qnqwyn6k.requirements.txt (line 31))
  Cloning https://github.com/dehui333/Porechop.git to /local/job_5014742/pip-req-build-a2scptry
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/dehui333/Porechop.git /local/job_5014742/pip-req-build-a2scptry
  remote: Support for password authentication was removed on August 13, 2021.
  remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
  fatal: Authentication failed for 'https://github.com/dehui333/Porechop.git/'
  error: subprocess-exited-with-error
  × git clone --filter=blob:none --quiet https://github.com/dehui333/Porechop.git /local/job_5014742/pip-req-build-a2scptry did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× git clone --filter=blob:none --quiet https://github.com/dehui333/Porechop.git /local/job_5014742/pip-req-build-a2scptry did not run successfully.
│ exit code: 128
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
CondaEnvException: Pip failed
</code>
</details>

where each `/path/to` was manually censored from the log.

- **Details:**

In general, never before have I been asked for password authentication when installing a conda env. So, I inspected the `herro-env.yml` file and found this line `git+https://github.com/dehui333/Porechop.git` in the `pip` section. I haven't seen such an install instruction before but, assuming that this works in general, I tried to look up the URL. However, if I copy+paste the `Porechop` URL into my browser I get an _Error 404: not found_. Also, when using GitHub's global search function there is (as of today) no public repository `Porechop` by a user `dehui333`.

- **System and setup:**
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
```
```
conda 24.1.2
```

**Comment by lfaino** [comment]
I think that i have the same issue

L

**Comment by faulk-lab** [comment]
I changed it to `git+https://github.com/rrwick/Porechop.git` and the conda completed. Let's see if the rest of the instructions work...

**Comment by faulk-lab** [comment]
Neither the sif nor the models are available because `http://complex.zesoi.fer.hr` is down. I tried to compile from source but it's so difficult b/c of the CUDA paths that I gave up. 

No matter how good the tool results are, it's irrelevant if it cannot be installed and used.

**Comment by sirselim** [comment]
Just linking this comment [here](https://github.com/lbcb-sci/herro/issues/33#issuecomment-2125549618) for reference.

The download links for the models and singularity image have been updated.

**Comment by Krannich479** [comment]
I close this issue since there are multiple suggested solutions by now:
- compile without Porechop
- run via ONT's dorado >= v0.7.0
