### ISSUE TITLE
Access to the models

### ISSUE THREAD

**Issue by qhelleu** [lbcb-sci/herro#3]
Hi, 
I would like to try Herro, as it looks very efficient. However, as many of us, I don't work on aws (and don't have an account). Is it possible to provide an other way to get access to the models and the image?

For the models, I would recommend using Zenodo (https://zenodo.org/). It is free and datasets can be up to 50 Gb, and your dataset will get a DOI and a direct download link. For the container image, I would recommend to store it in DockerHub (or the new github system), it will make it accessible and compatible with docker, singularity and apptainer users, and it will provide a version history.
Thanks for your program,
Best.

**Comment by dominikstanojevic** [comment]
Hello,

Thanks for your feedback and recommendations.

Users do not need an aws account to download the model and singularity image. Just set up the profile in aws-cli with the access key provided and you will be able to download both the model and singularity image.

We agree with you that the current solution is not the most user-friendly one. In the following days, we will try to provide an alternative method for easier downloading using wget/curl/etc.

Best regards,
Dominik

**Comment by dominikstanojevic** [comment]
Hello,

we have added new download links for:

1. [Model](http://complex.zesoi.fer.hr/data/downloads/model_v0.1.pt)
2. [Singularity image](http://complex.zesoi.fer.hr/data/downloads/herro.sif)
3. [Error-corrected HG002 UL reads](http://complex.zesoi.fer.hr/data/downloads/HG002.experimentalUL.corrected.fasta.gz)

Users can download files using wget/curl (no need for awscli). Check the README for more details.

**Comment by dasn588** [comment]
Hi Dominik,
Nihar here,

I tried to download model file using given link but could not download it.
I am getting following error;
wget -c **http://complex.zesoi.fer.hr/data/downloads/model_v0.1.pt**

--2024-05-30 09:07:43--  http://complex.zesoi.fer.hr/data/downloads/model_v0.1.pt
Resolving complex.zesoi.fer.hr (complex.zesoi.fer.hr)... 161.53.64.198
Connecting to complex.zesoi.fer.hr (complex.zesoi.fer.hr)|161.53.64.198|:80... failed: Connection timed out.
Retrying.

Please help me to resolve the issue or please share model files to my mail id (dasn588@gmail.com)

**Comment by dominikstanojevic** [comment]
Hello Nihar, 

please find the updated links here: https://github.com/lbcb-sci/herro?tab=readme-ov-file#model-download

For R10.4.1: `wget http://metals.zesoi.fer.hr:9080/herro/model_v0.1.pt`
For R9.4.1: `wget http://metals.zesoi.fer.hr:9080/herro/model_R9_v0.1.pt`

Best regards,
Dominik

**Comment by dasn588** [comment]
Hi Dominik,
Thank you for the response.
But still I am getting the same error.

wget http://metals.zesoi.fer.hr:9080/herro/model_v0.1.pt
--2024-05-30 15:13:14--  http://metals.zesoi.fer.hr:9080/herro/model_v0.1.pt
Resolving metals.zesoi.fer.hr (metals.zesoi.fer.hr)... 161.53.64.201
Connecting to metals.zesoi.fer.hr (metals.zesoi.fer.hr)|161.53.64.201|:9080... failed: Connection timed out.
Retrying.

--2024-05-30 15:15:25--  (try: 2)  http://metals.zesoi.fer.hr:9080/herro/model_v0.1.pt
Connecting to metals.zesoi.fer.hr (metals.zesoi.fer.hr)|161.53.64.201|:9080... failed: Connection timed out.
Retrying.

Can you share any other link for download.
