### ISSUE TITLE
Models inaccessible

### ISSUE THREAD

**Issue by qhelleu** [lbcb-sci/herro#38]
Hi,
Thanks for the great work. 
I would like to use Herro again on an old dataset, unfortunately the models are unavailable. Can you make them available again ? 
Please consider uploading them on Zenodo, as it would make them more accessible, and you can even do versioning.
Thanks,
All the best.
Quentin

**Comment by Tearinna** [comment]
Hi,
thank for the great work.
I would also like to download a model for R10.4.1 data but I confirm that the models are not accessible. I tried your command-line described in the documentation **"wget http://metals.zesoi.fer.hr:9080/herro/model_v0.1.pt"** but it doesn't work.
Thanks for your help
Best regards,
Tearinna

**Comment by dominikstanojevic** [comment]
Hello Tearinna,

The link works for me. Could you please specify what kind of error you're encountering?

Best regards,
Dominik

**Comment by Tearinna** [comment]
Hello Dominik,

thanks for your reply.

The error is :
Connection to metals.zesoi.fer.hr failed: Connection terminated due to connection timeout

Best regards,
Tearinna

**Comment by dominikstanojevic** [comment]
Hello,

try from Zenodo: https://zenodo.org/records/12683277

Best,
Dominik

**Comment by Tearinna** [comment]
Hello Dominik,

it works !! I have the model file

Thank you for your help

Best regards,
Tearinna

**Comment by dominikstanojevic** [comment]
Hello,

great!

Best,
Dominik
