### ISSUE TITLE
Question Regarding Error Rate Evaluation Using bamConcordance

### ISSUE THREAD

**Issue by Yichen-HNU** [lbcb-sci/herro#44]
Dear Lbcb-sci,

I am currently working on evaluating error correction using the bamConcordance script as described in your paper. In the appendix, you have provided instructions on how to use this script. However, the output files from the script contain error rates for each read individually.

I am particularly interested in understanding how you computed the overall mismatchBp, nonHpInsertionBp, nonHpDeletionBp, hpInsertionBp, and hpDeletionBp values for the entire dataset. I have attempted to calculate these metrics by summing all the errors and dividing by the total number of bases, as well as by first calculating the error rate for each read and then computing the overall error rate. However, neither approach matches the results provided in your paper for the A. thaliana dataset.

Could you please explain the method you used to calculate these overall error metrics? Your guidance would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Yichen

**Comment by dehui333** [comment]
My account was suspended by GitHub by mistake and I replied to this via email - apparently our methods for calculation were the same so the difference probably lied in previous steps such as reference used/alignment etc.
