### ISSUE TITLE
Cannot download models - server down?

### ISSUE THREAD

**Issue by tallnuttrbgv** [lbcb-sci/herro#48]
Hi,

I cannot download the models, get:

wget http://metals.zesoi.fer.hr:9080/herro/model_R9_v0.1.pt
--2024-08-02 12:25:46--  http://metals.zesoi.fer.hr:9080/herro/model_R9_v0.1.pt
Resolving metals.zesoi.fer.hr (metals.zesoi.fer.hr)... 161.53.64.201
Connecting to metals.zesoi.fer.hr (metals.zesoi.fer.hr)|161.53.64.201|:9080... failed: Connection timed out.
Retrying.

etc..

**Comment by dominikstanojevic** [comment]
Hi,

can you try:

For R10.4.1 data,

`wget -O model_R10_v0.1.pt https://zenodo.org/records/12683277/files/model_v0.1.pt?download=1`

For R9.4.1 data (experimental),

`wget -O model_R9_v0.1.pt https://zenodo.org/records/12683277/files/model_R9_v0.1.pt?download=1`

Best,
Dominik

**Comment by tallnuttrbgv** [comment]
Hi,

yes that worked,

Thanks.
