### ISSUE TITLE
`herro inference` keeps getting killed

### ISSUE THREAD

**Issue by JoanJong** [lbcb-sci/herro#60]
Hi,

I have an R10 non-UL dataset that I have re-basecalled using `dorado basecaller` (dna_r10.4.1_e8.2_400bps_sup@v5.0.0 model). The size of the file zipped is 108Gb. After basecalling, I used the basecalled file as input to the HERRO pipeline, i.e. preprocessing, batched alignment and then inference. For the batched alignment stage, I edited the minimap2 parameters according to the recommended parameters for non-UL reads in the Supplementary Materials of the preprint:

```
$minimap2 -K8g -cx ava-ont \
-k21 -w14 -f 0.005 -e100 -r150 -m1500 -z200 \
-t${num_threads} --dual=yes $reads $reads \
| $batch_script $rids - $outdir
```
I have tried different installations of HERRO and all gave problems:

1. Docker container

After showing parsing reads for ~4min, the program stopped abruptly without any error messages.

2. Compile by source

The program keeps stopping with the error message:

> 254115 Killed

The number was different for each attempt. I assumed it was due to memory issues, so I reran `herro inference` with different batch sizes (64, 32, 10, 5). All tries resulted in the same error.

3. Compile by source (debugging)

I compiled the version of HERRO using the link provided in a separate issue: https://github.com/lbcb-sci/herro/tree/decoding-debug. I still got the "Killed" error message.

### The commands used:

```
${HERRO_DIR}/scripts/preprocess.sh  ${FASTQ} ${SPECIES}_preproc 30 20

seqkit seq -ni ${FASTQ} > ${WORKDIR}/${SPECIES}_readIDs.txt

${HERRO_DIR}/scripts/create_batched_alignments.sh \
${SPECIES}_preproc.fastq.gz \
${WORKDIR}/${SPECIES}_readIDs.txt \
30 \
${WORKDIR}/${SPECIES}_batched_alignments

# Containing edited minimap2 params
herro inference \
--read-alns ${WORKDIR}/${SPECIES}_batched_alignments \
-m ${MODEL} \
-b 64 \
-d 0 \
-t 30 \
${WORKDIR}/${SPECIES}_preproc.fastq.gz \
${WORKDIR}/${SPECIES}_inference.fasta

```

### Specs:
Operating system: Windows 11 Pro, OS build 22631.3880
Hardware (CPUs, Memory, GPUs): CPU - 13th Gen Intel(R) Core(TM) i9-13900, 24 cores; GPU - NVIDIA RTX A6000
Source data location: Device
Details about data: PromethION 2 Solo, R10.4.1, simplex non-ultralong reads

**Comment by colindaven** [comment]
I'm not the dev, but it might be RAM (how much do you have?). 

I have seen massive RAM usage of 800GB+ with file sizes like this in `dorado correct` (yes, not Herro). Does it run through in `dorado correct`?

**Comment by JoanJong** [comment]
Hi,

Thanks for the suggestion. I have 64GB of RAM and I monitored the usage via Task Manager after rerunning the `herro inference` command. It seems like my GPU was not engaged at all and the program stopped when the RAM hit 43GB usage. I took a screenshot while the program was running and the GPU stayed at 0% until the program stopped: 

![gpu_not_used](https://github.com/user-attachments/assets/1e962295-4e0f-4883-9565-a2ffbb43fa9d)

Perhaps I have not specified the GPU correctly? I specified it as `-d 0` in the `herro inference` command. Below is the output of `nvidia-smi`:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76                 Driver Version: 552.23         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A6000               On  |   00000000:01:00.0 Off |                  Off |
| 30%   29C    P8              3W /  300W |    1078MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

```

**Comment by colindaven** [comment]
You have 108 GB of data and only 64 GB RAM. I don't think that is going to work. 

From the dorado correct page they recommend >256GB. I'd even double that for most datasets (I have run 20-30 so far).

https://github.com/nanoporetech/dorado?tab=readme-ov-file#read-error-correction

**Comment by JoanJong** [comment]
That would make sense why it did not work. I was assuming maybe the data would be split into batches to be processed separately, since the batched alignments were made. I have access to a supercomputer with sufficient RAM (500GB) so I will try to run HERRO there.

Thanks again!
