### ISSUE TITLE
herro's principle and phasing

### ISSUE THREAD

**Issue by dcopetti** [lbcb-sci/herro#9]
Hello,
can you please describe how herro's error correction steps work, and how you ensure the preservation of the phase between two variant sites within the same read? I see that, though N50 stats increase in your assemblies, switch and hamming rate remain the same.
Other questions:
Will herro work also with R9 data? Is there a minimum ONT coverage that the software needs to do the error correction? Can I run herro without GPUs?
Thanks,

Dario

**Comment by dominikstanojevic** [comment]
Hello Dario,

Herro uses informative positions (their combinations) to predict correct bases (and keep information about haplotypes) in cases where there is high variability (at least two bases are supported). A full description of the method will be available in the manuscript we plan to write soon.

Note: We're talking about the assembly switch and hamming error rate. Currently, this is just a preliminary result. We plan to do a fair estimation by focusing only on the regions assembled in all cases. Moreover, we have to explore the influence of homopolymers on the error rates (we expect they contribute significantly). Again, we will have more information published in the manuscript.

Yes, we're planning to release the R9 model soon. We're exploring the effect of coverage on the error correction (again, more information will be available in the manuscript). Haploid 30x will work, lower coverages should work too.

I can add support for CPU-based inference, just need some time to add the code and test. At this moment I cannot say how fast it would work.

Thanks for your interest in the tool. If you have any more questions or suggestions, feel free to contact me. 

Best regards,
Dominik

**Comment by dcopetti** [comment]
Thank you for the explanations Dominik, I am looking forward to reading the preprint!
Dario
